backend:
  name: git-gateway
  branch: master
  open_authoring: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "Open Workshop"
    label: "Open Workshop"
    folder: "content/workshops/openworkshops"
    description: "Workshop date, description, and links to class content."
    create: true
    editor:
     preview: false
    fields:
      - { label: "Placeholder", name: "placeholder", widget: "hidden", default: "false" }
      - { label: "Privacy Setting", name: "privacySetting", widget: "hidden", default: "open" }
      - { label: "Workshop Number", name: "workshopNum", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: Thumbnail, name: thumbnail, widget: image}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Readings", 
          name: "readings", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: false, widget: file},
            { label: URL, name: url, required: false, widget: string},
          ]}
      - { label: "Reading Files", 
          name: "readingFiles", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: true, widget: file},
          ]}
      - { label: "Reading Link", 
          name: "readingLinks", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: URL, name: url, required: true, widget: string}
          ]}
      - { label: "Lecture File", 
          name: "lectureFiles", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: true, widget: file},
          ]}
      - { label: "Lectures Links", 
          name: "lectureLinks", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: URL, name: url, required: true, widget: string}
          ]}
      - { label: "Links", 
          name: "links", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: URL, name: url, required: false, widget: string}
          ]}
      - { label: "Gallery Images", 
          name: "galleryImages", 
          widget: "list", 
          fields: [
            { label: Image, name: image, required: true, widget: image },
            { label: Alt Text, name: altText, required: true, widget: string}
          ]}
  - name: "Closed Workshop"
    label: "Closed Workshop"
    folder: "content/workshops/closedworkshops"
    description: "Private workshop date, description, and links to class content."
    create: true
    editor:
     preview: false
    fields:
      - { label: "Privacy Setting", name: "privacySetting", widget: "hidden", default: "closed" }
      - { label: "Workshop Number", name: "workshopNum", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: Thumbnail, name: thumbnail, widget: image}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Readings", 
          name: "readings", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: false, widget: file},
            { label: URL, name: url, required: false, widget: string},
          ]}
      - { label: "Reading Files", 
          name: "readingFiles", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: true, widget: file},
          ]}
      - { label: "Reading Link", 
          name: "readingLinks", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: URL, name: url, required: true, widget: string}
          ]}
      - { label: "Lecture File", 
          name: "lectureFiles", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: true, widget: file},
          ]}
      - { label: "Lectures Links", 
          name: "lectureLinks", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: URL, name: url, required: true, widget: string}
          ]}
      - { label: "Links", 
          name: "links", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: URL, name: url, required: false, widget: string}
          ]}
      - { label: "Gallery Images", 
          name: "galleryImages", 
          widget: "list", 
          fields: [
            { label: Image, name: image, required: true, widget: image },
            { label: Alt Text, name: altText, required: true, widget: string}
          ]}